name: CI-CD # nome do workflow

on: # evento que irá disparar o workflow
  push:
    branches: ["main"] # dispara a qualquer push na main
  workflow_dispatch: # permite execução manual do workflow
jobs: # sequência de etapas a serem executadas
  ci: # job de ci
    runs-on: ubuntu-latest
    steps: # passos a serem executados
      - name: Obter o código do projeto
        uses: actions/checkout@v4
      - name: Autenticar no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Construção da imagem Docker
        run: echo "Executando o comando Docker Build"
      - name: Envio da imagem Docker
        run: echo "Executando o comando Docker Push"

  cd: # job de cd
    runs-on: ubuntu-latest
    needs: [ci]
    steps: # passos a serem executados
      - name: Autenticar na AWS
        run: echo "Executando o comando aws configure"
      - name: Configurar o kubectl
        run: echo "Executando o comando aws eks update-kubeconfig"
      - name: Deploy os manifestos do kubernetes
        run: echo "Executando o comando kubectl apply"
